<?php

/**
 * Class-PSL.php
 *
 * @package Post Subject Length
 * @link
 * @author smftricks <diegoandres_cortes@outlook.com>
 * @copyright 2022 smftricks
 * @license https://opensource.org/licenses/MPL-2.0 Mozilla Public License 2.0
 *
 * @version 0.1
 */

/**
 * Generated by SimpleModMaker
 */
final class PSL
{
	public static function postEnd()
	{
		global $modSettings, $smcFunc, $topic, $context;

		// Respect the upper limit and do nothing if the setting is not set
		if (empty($modSettings['p_s_l_psl_subject_length']) || $modSettings['p_s_l_psl_subject_length'] > 255)
			return;

		$context['posting_fields']['subject']['input']['attributes']['size'] = $modSettings['p_s_l_psl_subject_length'];
		$context['posting_fields']['subject']['input']['attributes']['maxlength'] = $modSettings['p_s_l_psl_subject_length'] + (!empty($topic) ? $smcFunc['strlen']($context['response_prefix']) : 0);
	}

	public static function modifyPostSettings(&$config_vars)
	{
		global $txt;

		loadLanguage('PSL');
		$config_vars[] = array('int', 'p_s_l_psl_subject_length', 'subtext' => $txt['p_s_l_psl_subject_length_desc']);
	}
}
